"""Generate seed-variant train + eval configs for the Phase-25 multi-seed matched control.

The single-seed (42) point estimates need run-to-run variance before the headline crossover
(single-vector drops on novel, late interaction stays flat) can be reported as mean ± std rather
than a possible seed artifact. This stamps out, from the existing BASE configs, one variant per seed
that changes ONLY the seed and the per-seed output paths — nothing else — so every confound stays
matched across seeds exactly as in the base run.

For each base config and each seed it appends `_s<seed>` to `name` and to the paths that must be
unique per seed, and sets the seed field:
  - TRAIN config (`output_dir` present): `train.seed` = seed; suffix `output_dir` (checkpoint dir).
  - EVAL config (`index` present): top-level `seed` = seed; suffix `model.path` (the seed's
    checkpoint) and `index.dir` (a fresh index for the seed's weights). Shared, split-agnostic paths
    (e.g. `symbol_weighting.idf_path` -> the one token_idf.json) are left untouched.

The base train `output_dir` and the base eval `model.path` share a stem (e.g.
`.../li_ft_novel_bm25`), so the same suffix on both keeps the eval pointed at its own checkpoint.

    python scripts/make_seed_configs.py --seeds 1 2 3 4          # -> configs/seeds/*.yaml
    python scripts/make_seed_configs.py --seeds 1 2 3 4 --out-dir configs/seeds

Writes YAML only; runs nothing. `configs/seeds/` is git-ignored (derived from these base configs).
"""

from __future__ import annotations

import argparse
import copy
from pathlib import Path

import yaml

# The matched-control sweep: LI + SV, both splits. Base configs (seed 42) already exist and are the
# single source of truth; the sweep varies only the seed.
BASE_TRAIN = [
    "configs/train/li_ft_random.yaml",
    "configs/train/li_ft_novel.yaml",
    "configs/train/sv_ft_random_lr3e6.yaml",
    "configs/train/sv_ft_novel_lr3e6.yaml",
]
BASE_EVAL = [
    # LI, weighting OFF (pure architecture control)
    "configs/late_interaction_ft_random.yaml",
    "configs/late_interaction_ft_novel.yaml",
    # LI, reported IDF weighting (reuses the OFF run's index)
    "configs/late_interaction_ft_random_idf.yaml",
    "configs/late_interaction_ft_novel_idf.yaml",
    # matched single-vector control
    "configs/dense_sv_ft_random_lr3e6.yaml",
    "configs/dense_sv_ft_novel_lr3e6.yaml",
]

_GENERATED_HEADER = (
    "# GENERATED by scripts/make_seed_configs.py — do not edit by hand.\n"
    "# Seed variant of a base config; only the seed and per-seed output paths differ.\n"
)


def make_seed_config(base: dict, seed: int) -> dict:
    """Return a deep copy of `base` retargeted to `seed` (field rules in the module docstring)."""
    cfg = copy.deepcopy(base)
    suffix = f"_s{seed}"
    cfg["name"] = f"{cfg['name']}{suffix}"
    if "output_dir" in cfg:                       # TRAIN config
        cfg["train"]["seed"] = seed
        cfg["output_dir"] = f"{cfg['output_dir']}{suffix}"
    elif "index" in cfg:                          # EVAL config
        cfg["seed"] = seed
        cfg["model"]["path"] = f"{cfg['model']['path']}{suffix}"
        cfg["index"]["dir"] = f"{cfg['index']['dir']}{suffix}"
    else:
        raise ValueError(f"config {cfg.get('name')!r} is neither a train nor an eval config")
    return cfg


def _write(cfg: dict, out_dir: Path) -> Path:
    path = out_dir / f"{cfg['name']}.yaml"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(_GENERATED_HEADER)
        yaml.safe_dump(cfg, fh, sort_keys=False, default_flow_style=False)
    return path


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate seed-variant train+eval configs.")
    ap.add_argument("--seeds", type=int, nargs="+", required=True, help="seeds to stamp (1 2 3 4)")
    ap.add_argument("--out-dir", default="configs/seeds", help="output dir (default configs/seeds)")
    ap.add_argument("--repo-root", default=".", help="root holding the base configs (default .)")
    args = ap.parse_args()

    root = Path(args.repo_root)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    written = []
    for base_rel in BASE_TRAIN + BASE_EVAL:
        with open(root / base_rel, encoding="utf-8") as fh:
            base = yaml.safe_load(fh)
        for seed in args.seeds:
            written.append(_write(make_seed_config(base, seed), out_dir))

    print(f"wrote {len(written)} configs to {out_dir}/ for seeds {args.seeds}")
    for p in written:
        print(f"  {p.name}")


if __name__ == "__main__":
    main()
